// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AttributeContent: typeof import('./../components/bottomContent/AttributeContent.vue')['default']
    BottomContent: typeof import('./../components/bottomContent/BottomContent.vue')['default']
    Breadcrumb: typeof import('./../components/Breadcrumb.vue')['default']
    DictTag: typeof import('./../components/DictTag/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Event_vari: typeof import('./../components/event_vari/index.vue')['default']
    EventVariContent: typeof import('./../components/bottomContent/EventVariContent.vue')['default']
    NavItem: typeof import('./../components/NavItem.vue')['default']
    NavMenu: typeof import('./../components/NavMenu.vue')['default']
    PwdChange: typeof import('./../components/dialog/PwdChange.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tags: typeof import('./../components/Tags.vue')['default']
    TagsModule: typeof import('./../components/TagsModule.vue')['default']
  }
}
