const menuData = {
    userInfo: {
        userId: "49facfa5-c69d-4f6d-816d-4d1d2f360a9d",
        userLoginName: "admin",
        sex: 1,
        userName: "超级管理员",
        avatarLinkUrl: "",
        jobNumber: "001",
        mobilePhone: "",
    },
    funcInfo: [{
            funcId: "main",
            funcName: "首页",
            funcStatus: "",
            funcUrl: "/main",
            funcParentId: "",
            funcLevel: 1,
            funcOrderNum: 1,
            isShowMenu: true,
            icon: "",
        },
        {
            funcId: "xmcs",
            funcName: "项目测试",
            funcStatus: "",
            funcUrl: "/xmcs",
            funcParentId: "",
            funcLevel: 1,
            funcOrderNum: 1,
            isShowMenu: true,
            icon: "",
        },
        {
            funcId: "zdymk",
            funcName: "自定义模块",
            funcStatus: "",
            funcUrl: "/zdymk",
            funcParentId: "xmcs",
            funcLevel: 2,
            funcOrderNum: 1,
            isShowMenu: true,
            icon: "",
        },
        {
            funcId: "mokuaiyi",
            funcName: "模块一",
            funcStatus: "",
            funcUrl: "/mk",
            funcParentId: "zdymk",
            funcLevel: 3,
            funcOrderNum: 1,
            isShowMenu: true,
            icon: "",
        },
        {
            funcId: "jiekou",
            funcName: "接口",
            funcStatus: "",
            funcUrl: "/jiekou",
            funcParentId: "mokuaiyi",
            funcLevel: 4,
            funcOrderNum: 1,
            isShowMenu: true,
            icon: "",
        },
        {
            funcId: "suanfa",
            funcName: "算法",
            funcStatus: "",
            funcUrl: "/suanfa",
            funcParentId: "mokuaiyi",
            funcLevel: 4,
            funcOrderNum: 2,
            isShowMenu: true,
            icon: "",
        },
        {
            funcId: "ecc",
            funcName: "ECC",
            funcStatus: "",
            funcUrl: "/ecc",
            funcParentId: "mokuaiyi",
            funcLevel: 4,
            funcOrderNum: 3,
            isShowMenu: true,
            icon: "",
        },
        {
            funcId: "mokuaier",
            funcName: "模块二",
            funcStatus: "",
            funcUrl: "/mk",
            funcParentId: "zdymk",
            funcLevel: 3,
            funcOrderNum: 1,
            isShowMenu: true,
            icon: "",
        },
        {
            funcId: "jiekou2",
            funcName: "接口",
            funcStatus: "",
            funcUrl: "/jiekou",
            funcParentId: "mokuaier",
            funcLevel: 4,
            funcOrderNum: 1,
            isShowMenu: true,
            icon: "",
        },
        {
            funcId: "suanfa2",
            funcName: "算法",
            funcStatus: "",
            funcUrl: "/suanfa",
            funcParentId: "mokuaier",
            funcLevel: 4,
            funcOrderNum: 2,
            isShowMenu: true,
            icon: "",
        },
        {
            funcId: "ecc2",
            funcName: "ECC",
            funcStatus: "",
            funcUrl: "/ecc",
            funcParentId: "mokuaier",
            funcLevel: 4,
            funcOrderNum: 3,
            isShowMenu: true,
            icon: "",
        },
    ],
    deptList: [],
    postList: [],
};

export {
    menuData,
}